version: '3'

services:
  nginx:
    image: nginx:1.18-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf/app-nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - sample1_api
    links:
      - sample1_api
    # command: nginx -c /etc/nginx/nginx.conf

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql_initdb:/docker-entrypoint-initdb.d

  sample1_api:
    build: ./src/api
    container_name: "sample1_api"
    command: uwsgi --socket :8001 --module openapi_server --py-autoreload 1 --logto /tmp/mylog.log
    tty: true
    volumes:
      - ./src/api:/code
      - ./static:/static
    expose:
      - "8001"
    ports:
      - "8001:8001"
    depends_on:
      - db

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./src/openapi/sample1_api.yaml:/usr/share/nginx/html/sample1_api.yaml
    environment:
      API_URL: sample1_api.yaml

  openapi-cli:
     image: openapitools/openapi-generator-cli
     container_name: "openapi-cli"
     volumes:
      - /src:/local
      - /src/openapi:/local/openapi
      - /src/api:/local/api

